apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tutorial-db
  name: tutorial-db
spec:
  containers:
  - image: mariadb:10.3.8
    name: tutorial-db
    ports:
    - containerPort: 3306
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
